### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by sguinetti**
This pull request contains the lines to translate the application into Spanish. I hope this can improve it.

### CODE REVIEW

**Comment by kaputnikGo** [comment]
muchas gracias!
thank you for doing this, its amazing! i will merge it later today for the next release.

**Comment by kaputnikGo** [comment]
also, do you have a translation for "allowlist/blocklist"?
i'm removing blacklist/whitelist from the language used.
thanks

**Comment by sguinetti** [comment]
Nice to review. I'd translate as "lista de excepciones" because he's making an exception to Doze's service. Don't you think?

**Comment by kaputnikGo** [comment]
"lista de excepciones" does seem better, thank you. 
will merge and update the file today.

**Comment by kaputnikGo** [comment]
Hi, i have added a README section to the app which is meant to explain in greater detail how the various parts of the app work. i know its a lot to ask of you but if you have time would you be able to have a look at it ?

**Comment by sguinetti** [comment]
That would be great. But I won't be able to in the short term. When I can, I'll send a pull request.

**Comment by kaputnikGo** [comment]
Thank you so much for this!!

**Pull request merged**
